### ISSUE TITLE
Feature Request: have emcluster() return number of iterations

### ISSUE THREAD

**Issue by emilygoren** [snoweye/EMCluster#6]
The emcluster() function does not return the number of EM iterations performed, which would be useful for comparing different methods of initialization.

**Comment by snoweye** [comment]
I have some minimum changes to `emcluster()`. I did not test yet, so it may break somewhere. More changes I am aware below will come later when I have time.
- `conv.eps` seems incorrect.
- `short_*` needs changes.
- `ss_*` needs changes.

**Comment by snoweye** [comment]
@emilygoren The latest push should have the features working. Please check.

**Comment by emilygoren** [comment]
I tried a few test datasets and the new features are working as expected. Many thanks!
