### ISSUE TITLE
init.EM() crashes with small matrices

### ISSUE THREAD

**Issue by torockel** [snoweye/EMCluster#9]
Hi everyone,

Thank you for your package EMCluster. While using it, my R session crashed when the data matrix in `init.EM()` had too few rows. A small example that leads to this error:
```{r}
library(EMCluster)
x <- matrix(0, nrow = 1, ncol = 2)
init.EM(x, nclass = 2)
```
The example is not sensible as a use case. However, I use the `init.EM()` inside of another function and I tried to catch the error with `tryCatch()` which did not work because the R session completely terminated.

**Comment by maitra** [comment]
Thank you for this bug report. Indeed, this is an error that we never anticipated because we did not think of having anyone try nrow(x) > nclass. But it should not happen, since function is built to check for singularity (p.d.) of the variance-covariance matrix and then act accordingly.

**Comment by torockel** [comment]
Thank you for the fast reply. I know nrow(x) < nclass is not really sensible. In my use case it sometimes occurs because of some selections inside an imputation method that uses GMC. I can check manually for nrow(x) < nclass. However, if you could check inside the `init.EM()` function, it would be nice.

**Comment by snoweye** [comment]
[This](https://github.com/snoweye/EMCluster/commit/403126b09bd04489096c2dc6b02affe827b541ad) should fix the issue.

**Comment by torockel** [comment]
Thank you for the fast fix.
